#!/bin/sh
# new a tmux session with several windows

session_name='dev'
tmux new-session -d -s $session_name
tmux rename-window 'cereal'
tmux send-keys -t $session_name:'cereal'.1 "conda activate cereal" Enter "clear" Enter
tmux split-window -v -p 35
tmux send-keys -t $session_name:'cereal'.2 "conda activate cereal" Enter "clear" Enter
tmux split-window -h
tmux send-keys -t $session_name:'cereal'.3 "conda activate cereal" Enter "clear" Enter
tmux new-window -n 'lilac'
tmux send-keys -t $session_name:'lilac'.1 "conda activate lilac" Enter "clear" Enter
tmux split-window -v -p 35
tmux send-keys -t $session_name:'lilac'.2 "conda activate lilac" Enter "clear" Enter
tmux new-window -n 'opencv'
tmux send-keys -t $session_name:'opencv' "conda activate opencv" Enter "clear" Enter
tmux new-window -n 'tf'
tmux send-keys -t $session_name:'tf' "conda activate tf" Enter "clear" Enter
tmux -2 attach-session -d
