#!/bin/sh
# new a tmux session with several windows

session_name='dev'
tmux new-session -d -s $session_name
tmux rename-window 'cereal'
tmux send-keys -t $session_name:'cereal'.1 "conda activate cereal" Enter "clear" Enter
tmux split-window -v -p 35
tmux send-keys -t $session_name:'cereal'.2 "conda activate cereal" Enter "clear" Enter
tmux split-window -h
tmux send-keys -t $session_name:'cereal'.3 "conda activate cereal" Enter "clear" Enter
tmux new-window -n 'script'
tmux send-keys -t $session_name:'script'.1 "conda activate myenv" Enter "clear" Enter
tmux split-window -v -p 35
tmux send-keys -t $session_name:'script'.2 "conda activate myenv" Enter "clear" Enter
tmux new-window -n 'lilac'
tmux send-keys -t $session_name:'lilac' "conda activate lilac" Enter "clear" Enter
tmux new-window -n 'fun'
tmux send-keys -t $session_name:'fun' "conda activate myenv" Enter "clear" Enter
tmux -2 attach-session -d
