#!/bin/bash

echo 'stopping containers...'
if [[ -n "$( docker ps -a -q )" ]]; then
  docker stop $(docker ps -a -q)
fi

echo 'deleting containers...'
if [[ -n "$( docker ps -a -q )" ]] ; then
  docker rm $(docker ps -a -q)
fi

echo 'deleting images...'
if [[ -n "$( docker images -q )" ]] ; then
  docker rmi $(docker images -q)
fi

docker volume prune

